# Práctica Guiada de Laboratorio 2 - Inteligencia Artificial G1 (EAPIS) 2022-1

### Prof. Rolando A. Maguiña Pérez

## Introducción

Como sabemos, en buena parte de las sesiones de laboratorio se utilizará el lenguaje de programación de libre distribución denominado Python junto con sus bibliotecas; específicamente, en la sesión del 16 de Mayo del 2022 se usará la biblioteca NumPy, la cual junto con otra biblioteca de Python llamada Matplotlib, replica parcialmente las capacidades de procesamiento de matrices y de graficado de la plataforma computacional Matlab. 

Dicha biblioteca se pretende utilizar con mayor énfasis en la segunda parte del curso para la construcción de sistemas inteligentes basados en las técnicas denominadas Sistemas de Inferencia Difusa y Redes Neuronales Artificiales (RNA). 

## Objetivos Específicos 

- Conocer y aplicar la biblioteca de Python denominada NumPy
- Crear aplicaciones utilizando esta herramienta, los cuadernos computacionales.

# Bibliotecas de Python

## NumPy

### Arreglos en NumPy

Un array es un objeto y tiene propiedades (y métodos):
    
    PROPIEDAD                   DESCRIPCIÓN
    ndarray.shape               Tupla con las dimensiones.
    ndarray.ndim                Número de dimensiones.
    ndarray.size                Número de elementos.
    ndarray.itemsize            Tamaño de uno de los elementos en bytes.
    ndarray.nbytes              Tamaño total ocupado por los elementos.
    ndarray.dtype               Tipo de dato de los elementos.
    ndarray.real                Parte real.
    ndarray.imag                Parte imaginaria.


En seguida se presentan algunos ejemplos:

Primero importamos el NumPy

In [ ]:
import numpy as np

Generaremos una matriz de 6 elementos, conteniendo los números del 1 al 6 sin incluir el cero. Una manera de hacerlo es mediante las sgtes líneas de código:

In [ ]:
x = np.arange(6).reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

Le sumamos  1 al arreglo con:

In [ ]:
a = x[:, :] + 1
a

array([[1, 2, 3],
       [4, 5, 6]])

Aplicamos el método 'shape' para determinar las dimensiones del arreglo:

In [ ]:
a.shape

(2, 3)

Aplicamos ahora el método 'ndim' para determinar el número de dimensiones del arreglo:

In [ ]:
a.ndim

2

El número de elementos del arreglo lo obtenemos mediante el método 'size'

In [ ]:
a.size

6

In [ ]:
a.nbytes

24

El tipo de los datos lo podemos obtener con el método 'dtype'

In [ ]:
a.dtype

dtype('int32')

In [ ]:
a.real

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.imag

array([[0, 0, 0],
       [0, 0, 0]])

### Creación de arreglos

Es posible crear arreglos de varias maneras: 
1. A partir de secuencias (listas o tuplas) de PYTHON.

2. Haciendo uso de funciones propias de NUMPY.

3. Lectura de datos desde un archivo.

4. Copiando un array existente

Veremos las tres primeras:

#### 1. A partir de secuencias de PYTHON

        Formato: numpy.array(secuencia, tipo_dato)

EJM.

In [ ]:
import numpy

In [ ]:
numpy.array([1, 5, 4.3, 3.28])

array([1.  , 5.  , 4.3 , 3.28])

In [ ]:
tupla = (3, 5, 7.7)
tupla

(3, 5, 7.7)

Convertimos la tupla en un arreglo mediante:

In [ ]:
a2 = numpy.array(tupla)
a2

array([3. , 5. , 7.7])

In [ ]:
lista = [4, 6, 8.8, 9.1]
lista

[4, 6, 8.8, 9.1]

Convertimos la lista en un arreglo mediante:

In [ ]:
z = numpy.array(lista)
z

array([4. , 6. , 8.8, 9.1])

In [ ]:
a3 = numpy.array([])

In [ ]:
a3

array([], dtype=float64)

In [ ]:
a4 = numpy.array(["linea1", "linea2", 33], dtype="|S3")

En la salida  oservaremos que las cadenas están precedidas por una ‘b’. Este carácter sólo indica que la cadena es de tipo ‘bytestring’, el valor almacenado es la cadena entre comillas simples.

In [ ]:
a4

array([b'lin', b'lin', b'33'], dtype='|S3')

#####   1.1 Arreglos n-dimensionales

Otra manera de crear arreglos es a partir de una lista de listas.

In [ ]:
a = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=numpy.int32)

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### 2. Mediante el uso de funciones de NUMPY

##### 2.1 arange

    Formato: numpy.arange(start, stop, step, dtype=None)

Considerar que:

1. El “step” puede ser decimal.

2. El extremo final del intervalo no se incluye.

EJM.

In [ ]:
numpy.arange(5, 6, 0.1)

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9])

##### 2.2 linspace

Otra función que se puede usar es linspace.

    Formato: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False)

Devuelve un array en el que se ha dividido el intervalo [start, stop] (endpoint=True, por defecto) en “num” fragmentos.

EJM.

In [ ]:
numpy.linspace(5, 6, 5)

array([5.  , 5.25, 5.5 , 5.75, 6.  ])

En el sgte ejemplo, al establecer *endpoint=False* ya no muestra el valor final de 6; y dado que *retstep=True*, muestra el valor del fragmento. 

In [ ]:
numpy.linspace(5, 6, 5, False, True)

(array([5. , 5.2, 5.4, 5.6, 5.8]), 0.2)

##### 2.3 ones

    Formato: numpy.ones(shape, dtype=None)

- shape, es la forma del arreglo de salida (entero o lista/tupla). Si le pasamos una lista o tupla, crea un array n-dimensional con la forma (shape) dada por la lista/tupla.

- dtype, cualquiera de los tipos de datos de NUMPY.

EJM.

In [ ]:
numpy.ones([2, 3], dtype="int")

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
numpy.ones(4, dtype=numpy.complex128)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

##### 2.4 zeros

    Formato: numpy.zeros(shape, dtype=float)

Tiene un comportamiento análogo al de numpy.ones, sólo que crea un array n-dimensional con la forma (shape) dada por la lista/tupla, de ceros.

EJM.

In [ ]:
numpy.zeros([3, 2], dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

En la sgte línea de código se va a generar 2 arreglos de dimensiones 3x4.

In [ ]:
numpy.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### 3. Lectura de archivos

La función de lectura y sus parámetros dependen del formato del archivo.

Supongamos el fichero “datos.csv” con el formato siguiente:

line 1 -> objID , RAJ2000 , e_RAJ2000 , DEJ2000 , e_DEJ2000 , upmag , e_upmag , gpmag , e_gpmag , rpmag , e_rpmag , ipmag , e_ipmag , zpmag , e_zpmag , Jmag , e_Jmag , Hmag , e_Hmag , Kmag , e_Kmag

line 2 -> 1237657610717364296 ,138.692294 ,0.002 ,46.253899 ,0.002 ,18.049 ,0.015 ,16.904 ,0.033 ,16.448 ,0.02 ,16.289 ,0.015 ,16.21 ,0.018 ,15.348 ,0.059 ,14.914 ,0.073 ,15.065 ,0.162
...


1. La primera línea contiene el nombre de los campos.
2. Las siguientes, los valores de cada objeto, separados por comas.

La lectura de los datos del archivo se efectuará mediante la función *loadtxt()* de NumPy, la cual carga el archivo en una matriz. El delimitador por defecto es espacio en blanco, si es otro hay que pasarlo como segundo argumento delimiter (‘,’ en el caso de coma, ‘\t’ si es tabulador, etc).

Si el archivo tiene una cabecera podemos saltar las filas correspondientes con *skiprows* (pasar el valor 0 es equivalente a omitir este argumento, devolviendo todas las filas).

Para indicar columnas específicas a leer, pasamos el argumento *usecols=[...]* con sus índices; recordar que la primera columna corresponde al índice 0.

A continuación se indica el formato general para loadtext():

        Formato:  numpy.loadtxt(fname, dtype=numpy.float, comments="#", delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0) 
donde:

- fname: nombre del archivo.
- dtype: tipo de dato. 
- delimiter: delimitador (por defecto es espacio en blanco, ',' en el caso de que el delimitador sea una coma, '\t' si es tabulador).  
- usecols: permite indicar las columnas a leer.

EJM. Supongamos que tenemos un archivo "pru.txt" que contiene 5 datos de tres variables, los cuales están estructurados como columnas separados por comas, y que el archivo no tiene cabecera algna. Para leer dicha data usaremos el método 'loadtxt'. Para leer los datos usaremos el sgte código (en el parámetro delimiter se ha configurado ',' como separador):

In [ ]:
file = "C:\\Users\\rolan\\Desktop\\pru.txt"
datos = np.loadtxt(file, delimiter=",")

In [ ]:
print(datos)

[[ 1.   0.   0.5]
 [ 2.   0.  10.3]
 [ 3.   5.5  1.1]
 [ 4.   8.2  6.5]
 [ 5.  12.1 16.7]]


EJM. Supongamos ahora que tenemos otro archivo "pru1.txt" que contiene también 5 datos de tres variables, los cuales están estructurados como columnas separados por comas, y que el archivo tiene una cabecera con los nombres de las variables. Para leer los datos con 'loadtxt' usaremos el sgte código (en el parámetro delimiter se ha configurado ',' como separador):

In [ ]:
file = "C:\\Users\\rolan\\Desktop\\pru1.txt"
datos = np.loadtxt(file, delimiter=",", skiprows=1)

In [ ]:
print(datos)

[[-2.   0.4 10.3]
 [ 3.   5.5  1.2]
 [-4.   7.2  6.5]
 [ 8.  10.1 14.3]]


### Manejo de arreglos

Indexación: se refiere a la selección de elementos concretos del array.

1. Se accede a un elemento del array dando su posición en el array, mediante un índice entero entre corchetes ('[]')
                        nombre_array[posicion]
2. El primer índice es el 0 (como en C/C++).
3. Si el índice es mayor que el número de elementos de array, lanzará una excepción (IndexError).

            Tipo de selección                Sintaxis
        Un solo elemento                array[posicion]
        Varios elementos consecutivos   array[inicio:fin]
    Elementos en orden cualesquiera     array[[p1, p2,..., pn]]
                                donde [p1, ,...,pn] es una lista o array

**Nota**: los índices pueden tomar valores negativos; al igual que en las secuencias de PYTHON, cuentan las posiciones desde el final del array.

EJM.

In [ ]:
a = numpy.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1]

1

In [ ]:
a[7]

7

In [ ]:
a[1], a[-1]

(1, 9)

In [ ]:
a[3:-4]

array([3, 4, 5])

In [ ]:
a[0:9:2]

array([0, 2, 4, 6, 8])

Análisis del ejm: aquí se está aplicando el comando básico de Python para el rebanamiento start:stop:step donde el paso es de 2.

In [ ]:
a[[3, 5, 9]]

array([3, 5, 9])

#### EJERCICIOS
1. Cree un array que contenga los siguientes elementos: [1, 3., True, 'Hola Mundo']. ¿De qué tipo es este array?. Muéstrelo por pantalla.
2. Cree un array con 10 elementos en el intervalo [-2,2] y equidistantes entre ellos. Muestre por pantalla el array. Después muestre sólo el tercer y cuarto elemento.
3. Genere un array de tipo 'float' de dimensiones (4, 4). Debe contener números consecutivos del 1 al 16.
4. Dado el array 
        2 4 5 6
        0 3 7 4
        8 8 5 2
        1 5 6 1
     Seleccione con una instrucción el subarray de elementos 
        0 3 7 4
    Después, seleccione el subarray de elementos 
    
        2 5 8 8
 
5. Cree un array de enteros de dimensiones (3,3) y valores iguales a 0. Asigne el valor de 1 a las cuatro esquinas.
6. Se tienen registrados los valores de cordenadas (x, y) en las columnas del arreglo

    1.33 4.5
    
    30.0 10.7 
    
    70.2 0.5

Agregue a este arreglo las coordenadas (37.1, -3.6), enseguida transpóngalo. Muestre por pantalla las dimensiones del nuevo array.
7. ¿Se pueden sumar los arreglos a = [[1, 2, 3]] y b = [[0], [1], [0]]?. ¿Por qué?. De ser posible, ¿cuál es su suma?.

### Instrucciones para el envío de la solución

La solución de la Práctica Guiada de Laboratorio 2 IA G1 2022-1 "PGL2 IA-G1 2022-1" podrá enviarse como respuesta a la tarea del mismo nombre publicada en la clase de Classroom, hasta las 11:59 h del Viernes 20 de Mayo del 2022, en un archivo con extensión .ipynb. 

El documento deberá tener las sgtes características:
- Nombre del archivo: PGL2_IA_G1_EAPIS_2022-1_nombre-apellidos.ipynb.
- Todas las preguntas de la Práctica deben responderse en este mismo cuaderno computacional; la solución a cada pregunta debe registrarse en una celda debajo del plnteamiento de la misma, mencionando explícitamente como subtítulo: "Solución del ejercicio n", donde "n" corresponde al número del ejercicio.